#!/usr/bin/env bash
# Copyright (C) 2020, Robin Vobruba <hoijui.quaero@gmail.com>
# Licensed under the GPL v3, see LICENSE-GPLv3.md.
#
# Pre-generates some files,
# to be ready to run jekyll *build* or *serve*.

# Exit immediately on each error and unset variable;
# see: https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail/
#set -Eeuo pipefail
set -Eeu

script_dir=$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")

# CD to project root
cd "$script_dir/.."

# This creates a copy of all markdown files
# which is pre-processed with jekylls Liquid engine,
# but *not* converted to HTML.
for md in **.md
do
	md_txt="${md}.txt"
	{
		echo "---"
		echo "---"
		echo "{% include_relative $md %}"
	} > "$md_txt"
	echo "Created file '$md_txt', including '$md'."
done

mkdir -p _data

# Generate the RDF from the YAML
for part in training module resource
do
	if [ -f "./$part.yml" ]
	then
		# Copy meta-data file to jekylls data folder
		cp "$part.yml" "./_data/"
		# Generate the RDF from the YAML
		"$script_dir/yaml2rdf" \
			"_data/$part.yml" \
			"_data/$part.ttl" \
			"_data/Prefixes.pref"
		# Copy the generated RDF/Turtle file back to the repo root,
		# so it will be copied to the publish dir (e.g. _site)
		cp "_data/$part.ttl" ./
	fi
done
