#!/usr/bin/env bash
# Copyright (C) 2020, Robin Vobruba <hoijui.quaero@gmail.com>
# Licensed under the GPL v3, see LICENSE-GPLv3.md.
#
# Pre-generates some files,
# to be ready to run jekyll *build* or *serve*.

# Exit immediately on each error and unset variable;
# see: https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail/
#set -Eeuo pipefail
set -Eeu

script_dir=$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")

# CD to project root
cd "$script_dir/.."

# This creates a copy of all markdown files
# which is pre-processed with jekylls Liquid engine,
# but *not* converted to HTML.
for md in **.md
do
	md_txt="${md}.txt"
	{
		echo "---"
		echo "---"
		echo "{% include_relative $md %}"
	} > "$md_txt"
	echo "Created file '$md_txt', including '$md'."
done

# Copy meta-data file to jekylls data folder
mkdir -p _data
cp module.yml _data/

# Generate the RDF from the YAML
cd _data
"$script_dir/yaml2rdf"
cp module.ttl ../
cd ..
echo "Created file 'module.ttl', a conversion of 'module.yml' into RDF."

